# SOPS configuration
# Encrypts secrets with age key

creation_rules:
  # Match secret yaml files in service and provider directories
  - path_regex: (backups|outline|kanbn|dreamfinder|radicale|matrix|contact)/.*\.yaml$
    age: age1mkelwyppmll44ehjnarunmtamcxpee7jljyl475mlvxma7dm4f3q6lnmks
