services:
  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    restart: always
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - /home/nick/apps/site:/srv/site:ro
      - /home/nick/apps/invite:/srv/invite:ro
      - /srv/tech-world:/srv/tech-world:ro

volumes:
  caddy_data:
  caddy_config:
